implemented stuff

diff --git a/src/wav2 b/src/wav2
--- a/src/wav2
+++ b/src/wav2
@@ -22,32 +22,34 @@
 
 ### constants
 
-LONG_OPTS="help,flac,mp3,count,output:,indexing,artist:,title:,\
-year:,comment:,license,version"
-SHORT_OPTS="FMco:ia:t:y:m:h"
+LONG_OPTS="help,flac,mp3,count,output:,indexing,album:,artist:,comment:,\
+genre:,year:,license,version"
+SHORT_OPTS="hFMco:ia:r:m:g:y:"
 WAV2_VERSION="0.1.0"
 
 ### variables: options
 
 convert_to_flac=0
 convert_to_mp3=0
-count_total_tracks=0
-output_directory=
-parse_track_index=0
-tag_album_artist=
-tag_album_title=
-tag_album_year=
+count_tracks=0
+output_dir=
+parse_index=0
+tag_album=
+tag_artist=
 tag_comment=
+tag_genre=
+tag_year=
 
 ### variables: other
 
 files=
+files_number=0
 
 ### functions
 
 bad_exit() # prints error message and exits the program
 {
-    echo "$(basename $0): ${1:-"Unknown Error"}"  1>&2
+    echo "$(basename $0): ${1:-"unknown error"}"  1>&2
     exit 1
 }
 
@@ -65,10 +67,11 @@ Available options:
   -c,--count               Count number of FILES and write it as tag
   -o,--output OUT          Save converted files in OUT directory
   -i,--indexing            Parse numeric prefix of files and write as tag
-  -a,--artist STR          Write STR as «album artist» tag
-  -t,--title STR           Write STR as «album title» tag
-  -y,--year STR            Write STR as «year» tag
+  -a,--album STR           Write STR as «album» tag
+  -r,--artist STR          Write STR as «artist» tag
   -m,--comment STR         Write STR as «comment» tag
+  -g,--genre STR           Write STR as «genre» tag
+  -y,--year STR            Write STR as «year» tag
   --license                Show license of the program
   --version                Show version of the program
 EOF
@@ -108,7 +111,8 @@ parse_opts()
                                   --longoptions $LONG_OPTS -- "$@")
     test $? -ne 0 && bad_exit "parsing of command line options failed."
     eval set -- "$parsed_options"
-    while test "$1" != ""; do
+    while test "$1" != ""
+    do
         case "$1" in
             -h | --help     ) usage
                               exit
@@ -117,24 +121,27 @@ parse_opts()
                               ;;
             -M | --mp3      ) convert_to_mp3=1
                               ;;
-            -c | --count    ) count_total_tracks=1
+            -c | --count    ) count_tracks=1
                               ;;
             -o | --output   ) shift
-                              output_directory="$1"
+                              output_dir="$1"
                               ;;
-            -i | --indexing ) parse_track_index=1
+            -i | --indexing ) parse_index=1
                               ;;
-            -a | --artist   ) shift
-                              tag_album_artist="$1"
+            -a | --album    ) shift
+                              tag_album="$1"
                               ;;
-            -t | --title    ) shift
-                              tag_album_title="$1"
-                              ;;
-            -y | --year     ) shift
-                              tag_album_year="$1"
+            -r | --artist   ) shift
+                              tag_artist="$1"
                               ;;
             -m | --comment  ) shift
                               tag_comment="$1"
+                              ;;
+            -g | --genre    ) shift
+                              tag_genre="$1"
+                              ;;
+            -y | --year     ) shift
+                              tag_year="$1"
                               ;;
             --license       ) license
                               exit
@@ -143,7 +150,8 @@ parse_opts()
                               exit
                               ;;
             --              ) shift
-                              files="$@"
+                              files=("$@")
+                              files_number=$#
                               break
                               ;;
             ?               ) bad_exit "parsing error."
@@ -152,17 +160,43 @@ parse_opts()
     done
 }
 
+process_flac()
+{
+    local base_name=$(basename -s .wav "$1")
+    cmd="flac -8 --force"
+    if test $parse_index -ne 0
+    then
+        local index=
+        local name=
+        IFS=' '
+        read -r index name <<< "$base_name"
+        cmd="$cmd -T \"TRACKNUMBER=$index\""
+        cmd="$cmd -T \"TITLE=$name\""
+    else
+        cmd="$cmd -T \"TITLE=$base_name\""
+    fi
+    test $count_tracks -ne 0 && cmd="$cmd -T \"TRACKTOTAL=$files_number\""
+    test -n "$tag_artist"    && cmd="$cmd -T \"ARTIST=$tag_artist\""
+    test -n "$tag_genre"     && cmd="$cmd -T \"GENRE=$tag_genre\""
+    test -n "$tag_album"     && cmd="$cmd -T \"ALBUM=$tag_album\""
+    test -n "$tag_year"      && cmd="$cmd -T \"DATE=$tag_year\""
+    test -n "$tag_comment"   && cmd="$cmd -T \"COMMENT=$tag_comment\""
+    test -n "$output_dir"    && cmd="$cmd -o \"$output_dir/$base_name.flac\""
+    cmd="$cmd \"$1\""
+    eval $cmd
+}
+
+process_mp3()
+{
+    echo boo
+}
+
 ### main
 
-parse_opts $@
-
-echo "Convert to FLAC:    $convert_to_flac"
-echo "Convert to MP3:     $convert_to_mp3"
-echo "Count total tracks: $count_total_tracks"
-echo "Output directory:   $output_directory"
-echo "Parse track number: $parse_track_index"
-echo "Album artist:       $tag_album_artist"
-echo "Album title:        $tag_album_title"
-echo "Album year:         $tag_album_year"
-echo "Comment:            $tag_comment"
-echo "Files to process:   $files"
+parse_opts "$@"
+test -n "$output_dir" && mkdir -p "$output_dir"
+for i in "${files[@]}"
+do
+    test $convert_to_flac -ne 0 && process_flac "$i"
+    test $convert_to_mp3  -ne 0 && process_mp3  "$i"
+done
